'use client'

import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import type { PDFGenerationOptions, PDFGenerationResult } from '../types'

export async function captureElement(elementId: string): Promise<HTMLCanvasElement> {
  const element = document.getElementById(elementId)
  if (!element) {
    throw new Error(`Element #${elementId} not found`)
  }

  const canvas = await html2canvas(element, {
    scale: 2,
    useCORS: true,
    allowTaint: true,
    backgroundColor: '#ffffff',
    logging: false,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } as any)

  return canvas
}

async function addImagePages(
  pdf: jsPDF,
  imgData: string,
  imgWidth: number,
  imgHeight: number,
  contentWidth: number,
  top: number,
  bottom: number,
  left: number,
  isFirstPage: boolean,
  sectionTitle: string,
): Promise<void> {
  const pageHeight = pdf.internal.pageSize.getHeight()
  const availableHeight = pageHeight - top - bottom

  if (imgHeight <= availableHeight) {
    if (!isFirstPage) pdf.addPage()
    pdf.setFontSize(12)
    pdf.setTextColor(30, 58, 95)
    pdf.setFont('helvetica', 'bold')
    pdf.text(sectionTitle, left, top - 4)
    pdf.addImage(imgData, 'PNG', left, top, imgWidth, imgHeight)
  } else {
    // Multi-page slicing
    let remainingHeight = imgHeight
    let srcY = 0
    let pageIdx = 0

    while (remainingHeight > 0) {
      if (!isFirstPage || pageIdx > 0) pdf.addPage()

      pdf.setFontSize(12)
      pdf.setTextColor(30, 58, 95)
      pdf.setFont('helvetica', 'bold')
      const suffix = pageIdx > 0 ? ` (cont.)` : ''
      pdf.text(sectionTitle + suffix, left, top - 4)

      const sliceHeight = Math.min(remainingHeight, availableHeight)
      const sliceRatio = sliceHeight / imgHeight
      const sliceCanvasHeight = Math.round(imgHeight * sliceRatio)

      // Create a temporary canvas for this slice
      const tmpCanvas = document.createElement('canvas')
      tmpCanvas.width = imgWidth * 2
      tmpCanvas.height = sliceCanvasHeight * 2
      const ctx = tmpCanvas.getContext('2d')
      if (ctx) {
        const srcImg = new Image()
        srcImg.src = imgData
        await new Promise<void>((resolve) => {
          srcImg.onload = () => {
            ctx.drawImage(
              srcImg,
              0, srcY * 2, imgWidth * 2, sliceCanvasHeight * 2,
              0, 0, imgWidth * 2, sliceCanvasHeight * 2,
            )
            resolve()
          }
        })
        const sliceData = tmpCanvas.toDataURL('image/png')
        pdf.addImage(sliceData, 'PNG', left, top, contentWidth, sliceHeight)
      }

      srcY += sliceCanvasHeight
      remainingHeight -= sliceHeight
      pageIdx++
    }
  }
}

export async function generatePDF(options: PDFGenerationOptions): Promise<PDFGenerationResult> {
  try {
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4',
    })

    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()

    // Cover page
    pdf.setFillColor(5, 150, 105)
    pdf.rect(0, 0, pageWidth, 60, 'F')

    pdf.setTextColor(255, 255, 255)
    pdf.setFontSize(28)
    pdf.setFont('helvetica', 'bold')
    pdf.text('StatLab', pageWidth / 2, 28, { align: 'center' })

    pdf.setFontSize(12)
    pdf.setFont('helvetica', 'normal')
    pdf.text('Statistical Analysis Report', pageWidth / 2, 40, { align: 'center' })

    pdf.setTextColor(15, 23, 42)
    pdf.setFontSize(16)
    pdf.setFont('helvetica', 'bold')
    pdf.text(options.title, pageWidth / 2, 85, { align: 'center' })

    if (options.includeTimestamp) {
      pdf.setFontSize(10)
      pdf.setFont('helvetica', 'normal')
      pdf.setTextColor(100, 100, 100)
      const timestamp = new Date().toLocaleDateString('en-GB', {
        day: 'numeric',
        month: 'long',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      })
      pdf.text(`Generated: ${timestamp}`, pageWidth / 2, 100, { align: 'center' })
    }

    pdf.setDrawColor(5, 150, 105)
    pdf.setLineWidth(0.5)
    pdf.line(15, 270, pageWidth - 15, 270)
    pdf.setFontSize(9)
    pdf.setTextColor(150, 150, 150)
    pdf.text(
      'Generated by StatLab — Intelligent Statistical Analysis',
      pageWidth / 2,
      278,
      { align: 'center' }
    )

    const top = 25
    const bottom = 15
    const left = 15
    const right = 15
    const contentWidth = pageWidth - left - right

    // Capture each section
    for (let i = 0; i < options.sections.length; i++) {
      const section = options.sections[i]
      try {
        const canvas = await captureElement(section.elementId)
        const imgData = canvas.toDataURL('image/png')
        const imgWidth = contentWidth
        const imgHeight = (canvas.height * imgWidth) / canvas.width

        addImagePages(pdf, imgData, imgWidth, imgHeight, contentWidth, top, bottom, left, false, section.title)
      } catch {
        // Section not found — add a placeholder page
        pdf.addPage()
        pdf.setFontSize(12)
        pdf.setTextColor(100, 100, 100)
        pdf.text(`${section.title} — (content not available)`, left, 40)
      }
    }

    // Add page numbers
    const totalPages = pdf.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.setTextColor(150, 150, 150)
      pdf.text(
        `Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 8,
        { align: 'center' }
      )
    }

    pdf.save(options.fileName)
    return { success: true, fileName: options.fileName }
  } catch (error) {
    return { success: false, error: (error as Error).message }
  }
}

export default generatePDF

export type { PDFSection, PDFGenerationOptions, PDFGenerationResult } from '../types'
